//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        public int adminid { get; set; }
        public string adminname { get; set; }
        public string admincontact { get; set; }
        public string adminpass { get; set; }
        public string adminstatus { get; set; }
        [Compare("adminpass")]
        public string ConfirmPass { get; set; }
    }
}
