//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public int detailid { get; set; }
        public Nullable<int> detailorderid { get; set; }
        public string detailprice { get; set; }
        public Nullable<int> detailproductid { get; set; }
        public Nullable<int> orderpayment { get; set; }
        public virtual Product_Category Product_Category { get; set; }
        public virtual Order Order { get; set; }
    }
}
