//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderid { get; set; }
        public int orderuserid { get; set; }
        public int orderquantity { get; set; }
        public int orderproductid { get; set; }
        public double orderprodprice { get; set; }
        public int orderdetailid { get; set; }
    
        public virtual Order_Detail Order_Details { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
