//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderid { get; set; }
        public string orderuserid { get; set; }
        public string orderquantity { get; set; }
        public string ordershipname { get; set; }
        public string ordershipaddress { get; set; }
        public string ordercontact { get; set; }
        public string ordertracking { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
    }
}
