//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcel
    {
        public int parcelid { get; set; }
        public string parceltracknum { get; set; }
        public int parcelpayment { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
