//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int paymentid { get; set; }
        public string paymentuser { get; set; }
        public string paymentfile { get; set; }
        public Nullable<System.DateTime> paymentdate { get; set; }
    }
}
