//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int productid { get; set; }
        [DisplayName("Product Name")]
        [Required]
        public string productname { get; set; }
        [DisplayName("Product Price")]
        [Required]
        public string productprice { get; set; }
        [DisplayName("Product Description")]
        [Required]
        public string productdesc { get; set; }
        [DisplayName("Product Image")]
        [Required]
        public string productimage { get; set; }
        [DisplayName("Product Category")]
        [Required]
        public Nullable<int> prodcategory { get; set; }
        [DisplayName("Product Update Dates")]
        [Required]
        public Nullable<System.DateTime> produpdatedate { get; set; }
    }
}
